CREATE SEQUENCE SQ_IDEMAIL;
CREATE SEQUENCE SQ_IDEMAILDESTINATARIO;


CREATE TABLE EMAIL (
		ID NUMBER NOT NULL,
		TEMPLATE VARCHAR2(40),
		DTSOLICITACAO DATE,
		IDAGENDAMENTO NUMBER
	);

ALTER TABLE EMAIL ADD CONSTRAINT PK_CONTROLE_EMAIL PRIMARY KEY (ID);




CREATE TABLE DESTINATARIO (
		ID NUMBER NOT NULL,
		EMAIL_ID NUMBER NOT NULL,
		EMAIL_DESTINATARIO VARCHAR2(100)
	);

ALTER TABLE DESTINATARIO ADD CONSTRAINT PK_CONTROLE_EMAIL_DESTINATARIO PRIMARY KEY (ID, EMAIL_ID);

ALTER TABLE DESTINATARIO ADD CONSTRAINT FK_CONTROLE_EMAIL_DEST FOREIGN KEY (EMAIL_ID)
	REFERENCES EMAIL (ID);

